apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: example-network
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "example-bridge",
      "ipam": {
          "type": "host-local",
          "ranges": [
            [{"subnet": "10.10.0.0/16"}]
          ],
          "routes": [{"dst": "0.0.0.0/0"}],
          "gateway": "10.10.0.1"
      }
  }'
